# A CertificateSigningRequest (CSR) resource is used to request that a 
# certificate be signed by a denoted signer, after which the request 
# may be approved or denied before finally being signed.


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: john-developer # CSR for John
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - list
  - get


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvviewer-role
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - persistentVolumes
  verbs:
  - list

