# this toleration allows pod to schedule on node with 
# key=value:Noschedule
# Where kubectl taint nodes node01 mortein=spray:Noschedule
apiVersion: v1
kind: Pod
metadata:
  name: bee
spec:
  containers:
  - image: nginx
    name: bee
  tolerations:
  - key: spray
    value: mortein
    effect: NoSchedule
    operator: Equal