- name: Install and configure supporting packages for Cassandra
  hosts: all
  become: true
  tasks:

  - name: Install Python and Java
    apt:
      name:
      - ""
      - ""

  - name: Assigning python alias to python2
    community.general.alternatives:
      name: python3
      link: /usr/bin/python
      path: /usr/bin/python3


  - name: Printing python and java versions to make sure installation was correct
    shell: 'python -V && java -version'
    register: command_output
   
   # Check java version
  - debug:
      var: command_output.stderr_lines

   # Check python version
  - debug:
      var: command_output.stdout_lines